// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RerangeHubLogic$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RerangeHubLogic";
  readonly sourceName: "contracts/libraries/RerangeHubLogic.sol";
  readonly abi: [{"inputs":[],"name":"InvalidConfig","type":"error"},{"inputs":[],"name":"InvalidDirection","type":"error"},{"inputs":[],"name":"RerangeNotReady","type":"error"},{"inputs":[],"name":"ToxicPrice","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220427c4b88842745c8cd73db05c3636bb08638cd78566ad344d81381bfd1aeed5464736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220427c4b88842745c8cd73db05c3636bb08638cd78566ad344d81381bfd1aeed5464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RerangeHubLogic.sol";
  readonly buildInfoId: "solc-0_8_28-6c7b7b35bc3355235d03f41871d0e700932ccc8c";
}

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RerangeHubLogic"]: RerangeHubLogic$Type;
    ["contracts/libraries/RerangeHubLogic.sol:RerangeHubLogic"]: RerangeHubLogic$Type;
  }
}
