// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RerangeTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RerangeTypes";
  readonly sourceName: "contracts/libraries/RerangeTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212208fe53f7f9dd7aea2b4407772a7df936becd3b89068da630727dcb1b9bbd166cd64736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212208fe53f7f9dd7aea2b4407772a7df936becd3b89068da630727dcb1b9bbd166cd64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RerangeTypes.sol";
  readonly buildInfoId: "solc-0_8_28-6c7b7b35bc3355235d03f41871d0e700932ccc8c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RerangeTypes"]: RerangeTypes$Type;
    ["contracts/libraries/RerangeTypes.sol:RerangeTypes"]: RerangeTypes$Type;
  }
}