// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RerangeHubFees$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RerangeHubFees";
  readonly sourceName: "contracts/libraries/RerangeHubFees.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220b910156f37cc2a6be11113675780aaf6003d3c01e52f37da578906ad9763da5464736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220b910156f37cc2a6be11113675780aaf6003d3c01e52f37da578906ad9763da5464736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RerangeHubFees.sol";
  readonly buildInfoId: "solc-0_8_28-98db12bf40c3b37b4423ba6b7b24cb76e04ab44e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RerangeHubFees"]: RerangeHubFees$Type;
    ["contracts/libraries/RerangeHubFees.sol:RerangeHubFees"]: RerangeHubFees$Type;
  }
}