// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RerangeHubVaults$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RerangeHubVaults";
  readonly sourceName: "contracts/libraries/RerangeHubVaults.sol";
  readonly abi: [{"inputs":[],"name":"InvalidVault","type":"error"},{"inputs":[],"name":"Unauthorized","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122028da20d4e8151efaab2028ac86cd89241820270636ebf9e0ca60f4c1729e1f9064736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122028da20d4e8151efaab2028ac86cd89241820270636ebf9e0ca60f4c1729e1f9064736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RerangeHubVaults.sol";
  readonly buildInfoId: "solc-0_8_28-6c7b7b35bc3355235d03f41871d0e700932ccc8c";
}

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RerangeHubVaults"]: RerangeHubVaults$Type;
    ["contracts/libraries/RerangeHubVaults.sol:RerangeHubVaults"]: RerangeHubVaults$Type;
  }
}
