// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FixedPoint96$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FixedPoint96";
  readonly sourceName: "contracts/libraries/uniswap/v3/FixedPoint96.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212202422dbf3bead30d3b1c29952843c1b267518bbcdb0d91366ac72877a7285e6fc64736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212202422dbf3bead30d3b1c29952843c1b267518bbcdb0d91366ac72877a7285e6fc64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/uniswap/v3/FixedPoint96.sol";
  readonly buildInfoId: "solc-0_8_28-ca3dcbdc8f0a60dda9bb520ec299f9217d71c6f1";
}

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FixedPoint96"]: FixedPoint96$Type;
    ["contracts/libraries/uniswap/v3/FixedPoint96.sol:FixedPoint96"]: FixedPoint96$Type;
  }
}
