// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface LiquidityAmounts$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "LiquidityAmounts";
  readonly sourceName: "contracts/libraries/uniswap/v3/LiquidityAmounts.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220feed2716c87d71b8289444b3f55966748a3d8e73d012a706399a1ee592c1c5b664736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220feed2716c87d71b8289444b3f55966748a3d8e73d012a706399a1ee592c1c5b664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/uniswap/v3/LiquidityAmounts.sol";
  readonly buildInfoId: "solc-0_8_28-ca3dcbdc8f0a60dda9bb520ec299f9217d71c6f1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["LiquidityAmounts"]: LiquidityAmounts$Type;
    ["contracts/libraries/uniswap/v3/LiquidityAmounts.sol:LiquidityAmounts"]: LiquidityAmounts$Type;
  }
}