// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RerangeHubActions$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RerangeHubActions";
  readonly sourceName: "contracts/libraries/RerangeHubActions.sol";
  readonly abi: [{"inputs":[],"name":"AdapterNotAllowed","type":"error"},{"inputs":[],"name":"InvalidConfig","type":"error"},{"inputs":[],"name":"InvalidNativeValue","type":"error"},{"inputs":[],"name":"TransferFailed","type":"error"},{"inputs":[],"name":"ZeroCapital","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220490dfae58dd20a812fdb3bafce2ce9d1d49f6b7d820b3ee8dcc01a439ffd62d064736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220490dfae58dd20a812fdb3bafce2ce9d1d49f6b7d820b3ee8dcc01a439ffd62d064736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RerangeHubActions.sol";
  readonly buildInfoId: "solc-0_8_28-6c7b7b35bc3355235d03f41871d0e700932ccc8c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RerangeHubActions"]: RerangeHubActions$Type;
    ["contracts/libraries/RerangeHubActions.sol:RerangeHubActions"]: RerangeHubActions$Type;
  }
}