// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RerangeHubViews$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RerangeHubViews";
  readonly sourceName: "contracts/libraries/RerangeHubViews.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220ee6edbc205087693cc521482d5e85271e36c65a687733c5a5086bcf2a5e2164164736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220ee6edbc205087693cc521482d5e85271e36c65a687733c5a5086bcf2a5e2164164736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RerangeHubViews.sol";
  readonly buildInfoId: "solc-0_8_28-98db12bf40c3b37b4423ba6b7b24cb76e04ab44e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RerangeHubViews"]: RerangeHubViews$Type;
    ["contracts/libraries/RerangeHubViews.sol:RerangeHubViews"]: RerangeHubViews$Type;
  }
}