// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RerangeHubOrders$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RerangeHubOrders";
  readonly sourceName: "contracts/libraries/RerangeHubOrders.sol";
  readonly abi: [{"inputs":[],"name":"UnknownOrder","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122090fe1a5475edfed7e178525a230b565fa22f93aaaee06bd81e7a0136003872e764736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122090fe1a5475edfed7e178525a230b565fa22f93aaaee06bd81e7a0136003872e764736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/RerangeHubOrders.sol";
  readonly buildInfoId: "solc-0_8_28-98db12bf40c3b37b4423ba6b7b24cb76e04ab44e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RerangeHubOrders"]: RerangeHubOrders$Type;
    ["contracts/libraries/RerangeHubOrders.sol:RerangeHubOrders"]: RerangeHubOrders$Type;
  }
}