// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface UniswapV4Types$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "UniswapV4Types";
  readonly sourceName: "contracts/libraries/uniswap/v4/UniswapV4Types.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea26469706673582212200eadaa73b05f56266314f630b1e978eaeef0e89df39b073bfdd580c792e0fe1a64736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea26469706673582212200eadaa73b05f56266314f630b1e978eaeef0e89df39b073bfdd580c792e0fe1a64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/uniswap/v4/UniswapV4Types.sol";
  readonly buildInfoId: "solc-0_8_28-ca3dcbdc8f0a60dda9bb520ec299f9217d71c6f1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["UniswapV4Types"]: UniswapV4Types$Type;
    ["contracts/libraries/uniswap/v4/UniswapV4Types.sol:UniswapV4Types"]: UniswapV4Types$Type;
  }
}