// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TickMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TickMath";
  readonly sourceName: "contracts/libraries/uniswap/v3/TickMath.sol";
  readonly abi: [{"inputs":[],"name":"InvalidTick","type":"error"}];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220191aa4756aa11b40ccf5d9ed38d21f19337544c8b4eb558dd7c6f7f1500fe64264736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220191aa4756aa11b40ccf5d9ed38d21f19337544c8b4eb558dd7c6f7f1500fe64264736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/uniswap/v3/TickMath.sol";
  readonly buildInfoId: "solc-0_8_28-ca3dcbdc8f0a60dda9bb520ec299f9217d71c6f1";
}

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TickMath"]: TickMath$Type;
    ["contracts/libraries/uniswap/v3/TickMath.sol:TickMath"]: TickMath$Type;
  }
}
