// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface FullMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "FullMath";
  readonly sourceName: "contracts/libraries/uniswap/v3/FullMath.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea2646970667358221220a2b5ae86e696ba07e4d8db143422ece3848442d41f4714ba8c0fd06704f4cd0864736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea2646970667358221220a2b5ae86e696ba07e4d8db143422ece3848442d41f4714ba8c0fd06704f4cd0864736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/uniswap/v3/FullMath.sol";
  readonly buildInfoId: "solc-0_8_28-ca3dcbdc8f0a60dda9bb520ec299f9217d71c6f1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["FullMath"]: FullMath$Type;
    ["contracts/libraries/uniswap/v3/FullMath.sol:FullMath"]: FullMath$Type;
  }
}