// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IOrderReader$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IOrderReader";
  readonly sourceName: "contracts/interfaces/IOrderReader.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"orderKey","type":"bytes32"}],"name":"getOrder","outputs":[{"components":[{"internalType":"address","name":"vault","type":"address"},{"internalType":"address","name":"adapter","type":"address"},{"internalType":"address","name":"token0","type":"address"},{"internalType":"address","name":"token1","type":"address"},{"internalType":"uint256","name":"capital","type":"uint256"},{"internalType":"bool","name":"isSell","type":"bool"},{"internalType":"int24","name":"targetTick","type":"int24"},{"internalType":"uint24","name":"triggerTicks","type":"uint24"},{"internalType":"bytes","name":"adapterData","type":"bytes"},{"internalType":"address","name":"referrer","type":"address"},{"internalType":"bool","name":"keepBalancesInVault","type":"bool"},{"internalType":"bool","name":"unwrapOut","type":"bool"},{"internalType":"bool","name":"closed","type":"bool"},{"internalType":"uint32","name":"rerangeCount","type":"uint32"},{"internalType":"uint40","name":"createdAt","type":"uint40"},{"internalType":"uint40","name":"lastRerangeAt","type":"uint40"},{"internalType":"uint256","name":"accruedFee0","type":"uint256"},{"internalType":"uint256","name":"accruedFee1","type":"uint256"},{"internalType":"uint256","name":"idle0","type":"uint256"},{"internalType":"uint256","name":"idle1","type":"uint256"}],"internalType":"struct RerangeTypes.Order","name":"","type":"tuple"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IOrderReader.sol";
  readonly buildInfoId: "solc-0_8_28-6c7b7b35bc3355235d03f41871d0e700932ccc8c";
}

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IOrderReader"]: IOrderReader$Type;
    ["contracts/interfaces/IOrderReader.sol:IOrderReader"]: IOrderReader$Type;
  }
}
